export const SERVICE_UNIT_OPTIONS = [
  { value: "Răng", label: "Răng" },
  { value: "1 Hàm", label: "1 Hàm" },
  { value: "2 Hàm", label: "2 Hàm" },
  { value: "Lần", label: "Lần" },
  { value: "Cái", label: "Cái" },
  { value: "Cặp", label: "Cặp" },
  { value: "Chốt", label: "Chốt" },
  { value: "Máng", label: "Máng" },
];

export const SERVICE_GROUP_OPTIONS = [
  { value: "Bệnh án", label: "Bệnh án" },
  { value: "Cắm chốt nội tuỷ", label: "Cắm chốt nội tuỷ" },
  { value: "Cắt lợi", label: "Cắt lợi" },
  { value: "Cắt phanh", label: "Cắt phanh" },
  { value: "Chỉnh nha", label: "Chỉnh nha" },
  { value: "Chỉnh nha Clear Correct", label: "Chỉnh nha Clear Correct" },
  { value: "Chỉnh nha Invisalign", label: "Chỉnh nha Invisalign" },
  { value: "Chỉnh nha MC KL thông minh", label: "Chỉnh nha MC KL thông minh" },
  { value: "Chỉnh nha MC KL thường", label: "Chỉnh nha MC KL thường" },
  { value: "Chỉnh nha MC ML hai hàm", label: "Chỉnh nha MC ML hai hàm" },
  { value: "Chỉnh nha MC ML hàm trên", label: "Chỉnh nha MC ML hàm trên" },
  { value: "Chỉnh nha MC sứ thông minh", label: "Chỉnh nha MC sứ thông minh" },
  { value: "Chỉnh nha MC sứ thường", label: "Chỉnh nha MC sứ thường" },
  { value: "Chụp 2D", label: "Chụp 2D" },
  { value: "Chụp 3D", label: "Chụp 3D" },
  { value: "Chụp x-quang", label: "Chụp x-quang" },
  { value: "Dự phòng sâu răng", label: "Dự phòng sâu răng" },
  {
    value: "Điều trị tuỷ răng vĩnh viễn",
    label: "Điều trị tuỷ răng vĩnh viễn",
  },
  { value: "Điều trị tuỷ răng sữa", label: "Điều trị tuỷ răng sữa" },
  { value: "Gắn đá", label: "Gắn đá" },
  { value: "Gắn răng", label: "Gắn răng" },
  { value: "Ghép mô", label: "Ghép mô" },
  { value: "Ghép xương", label: "Ghép xương" },
  { value: "Hàm / implant", label: "Hàm / implant" },
  { value: "Hàm giữ khoảng", label: "Hàm giữ khoảng" },
  { value: "Hàn cổ răng", label: "Hàn cổ răng" },
  { value: "Hàn răng sữa", label: "Hàn răng sữa" },
  { value: "Hàn răng vĩnh viễn", label: "Hàn răng vĩnh viễn" },
  { value: "Hàn thẩm mỹ", label: "Hàn thẩm mỹ" },
  { value: "Implant Hàn Quốc", label: "Implant Hàn Quốc" },
  { value: "Implant Mỹ", label: "Implant Mỹ" },
  { value: "Implant Pháp", label: "Implant Pháp" },
  { value: "Implant Thuỵ Sỹ", label: "Implant Thuỵ Sỹ" },
  { value: "Khám tư vấn", label: "Khám tư vấn" },
  { value: "Khí cụ chỉnh nha", label: "Khí cụ chỉnh nha" },
  {
    value: "Làm sạch răng và điều trị viêm lợi",
    label: "Làm sạch răng và điều trị viêm lợi",
  },
  { value: "Máng giãn cơ", label: "Máng giãn cơ" },
  { value: "Máng phẫu thuật", label: "Máng phẫu thuật" },
  { value: "Nâng xoang hở", label: "Nâng xoang hở" },
  { value: "Nâng xoang kín", label: "Nâng xoang kín" },
  { value: "Nhổ răng khôn", label: "Nhổ răng khôn" },
  { value: "Nhổ răng sữa", label: "Nhổ răng sữa" },
  { value: "Nhổ răng thường", label: "Nhổ răng thường" },
  { value: "Răng kim loại / Implant", label: "Răng kim loại / Implant" },
  { value: "Răng sứ kim loại", label: "Răng sứ kim loại" },
  { value: "Răng toàn sứ", label: "Răng toàn sứ" },
  { value: "Răng toàn sứ / Implant", label: "Răng toàn sứ / Implant" },
  { value: "Tạo hình xương", label: "Tạo hình xương" },
  { value: "Tẩy trắng răng", label: "Tẩy trắng răng" },
  { value: "Tháo lắp bán hàm", label: "Tháo lắp bán hàm" },
  { value: "Tháo lắp toàn hàm", label: "Tháo lắp toàn hàm" },
];

export const DEPARTMENT_OPTIONS = [
  { value: "Cắn khớp", label: "Cắn khớp" },
  { value: "Chỉnh nha", label: "Chỉnh nha" },
  { value: "X-quang", label: "X-quang" },
  { value: "Tháo lắp", label: "Tháo lắp" },
  { value: "Hàn răng", label: "Hàn răng" },
  { value: "Implant", label: "Implant" },
  { value: "Nha chu", label: "Nha chu" },
  { value: "Nội nha", label: "Nội nha" },
  { value: "Răng sứ", label: "Răng sứ" },
  { value: "Răng trẻ em", label: "Răng trẻ em" },
  { value: "Tẩy trắng răng", label: "Tẩy trắng răng" },
  { value: "Tiểu phẫu", label: "Tiểu phẫu" },
  { value: "Tổng quát", label: "Tổng quát" },
];
